global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "bisq-relay"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - "localhost:9400"
    relabel_configs:
      - target_label: service
        replacement: relay
